# Generated by Django 2.1.2 on 2018-11-03 03:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20181102_2310'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='post_description',
        ),
    ]
