# Generated by Django 2.1.2 on 2018-11-03 12:02

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20181103_1743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_description',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
