# Generated by Django 2.1.2 on 2018-11-05 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20181103_1802'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'get_latest_by': 'pub_date'},
        ),
    ]
