# Generated by Django 2.1.2 on 2018-11-07 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_auto_20181105_2247'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='previous_post',
            field=models.ForeignKey(blank=True, null=True, on_delete=None, to='blog.Post'),
        ),
    ]
