# Generated by Django 2.1.2 on 2018-11-07 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_post_next_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='next_post',
        ),
        migrations.RemoveField(
            model_name='post',
            name='previous_post',
        ),
    ]
