# Generated by Django 2.1.2 on 2018-11-09 17:30

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_auto_20181107_2255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_description',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
